name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # fix
      - fix
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    
    - name: Sync
      env:
        dest: 'root@123.60.69.41:/root/demo/public'
      run: |
        echo "${{secrets.ERVER_SSH_KEY}}" > KeyPair-a76a
        chmod 700 ./KeyPair-a76a.pem
        rsync -chav --delete \
          -e 'ssh -i ./KeyPair-a76a.pem -o StrictHostKeyChecking=no' \
          --exclude /deploy_key.pem \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /node_modules/ \
          ./ ${{env.dest}}