name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # fix
      - fix
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: build # 这是要复制到华为云静态服务器的文件夹名称
          REMOTE_HOST: '123.60.69.41' # 你的华为云公网地址
          REMOTE_USER: root # 华为登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /root/demo/public # 打包后的 dist 文件夹将放在 /root/node-server